// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/evidence/v1beta1/tx.proto

package proto.cosmos.evidence.v1beta1;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgSubmitEvidenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.evidence.v1beta1.MsgSubmitEvidence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string submitter = 1;</code>
     */
    java.lang.String getSubmitter();
    /**
     * <code>string submitter = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubmitterBytes();

    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    boolean hasEvidence();
    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    com.google.protobuf.Any getEvidence();
    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder();
  }
  /**
   * <pre>
   * MsgSubmitEvidence represents a message that supports submitting arbitrary
   * Evidence of misbehavior such as equivocation or counterfactual signing.
   * </pre>
   *
   * Protobuf type {@code cosmos.evidence.v1beta1.MsgSubmitEvidence}
   */
  public  static final class MsgSubmitEvidence extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.evidence.v1beta1.MsgSubmitEvidence)
      MsgSubmitEvidenceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgSubmitEvidence.newBuilder() to construct.
    private MsgSubmitEvidence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgSubmitEvidence() {
      submitter_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgSubmitEvidence(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              submitter_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (evidence_ != null) {
                subBuilder = evidence_.toBuilder();
              }
              evidence_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(evidence_);
                evidence_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.class, proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.Builder.class);
    }

    public static final int SUBMITTER_FIELD_NUMBER = 1;
    private volatile java.lang.Object submitter_;
    /**
     * <code>string submitter = 1;</code>
     */
    public java.lang.String getSubmitter() {
      java.lang.Object ref = submitter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        submitter_ = s;
        return s;
      }
    }
    /**
     * <code>string submitter = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubmitterBytes() {
      java.lang.Object ref = submitter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        submitter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVIDENCE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any evidence_;
    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    public boolean hasEvidence() {
      return evidence_ != null;
    }
    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    public com.google.protobuf.Any getEvidence() {
      return evidence_ == null ? com.google.protobuf.Any.getDefaultInstance() : evidence_;
    }
    /**
     * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
     */
    public com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder() {
      return getEvidence();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubmitterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, submitter_);
      }
      if (evidence_ != null) {
        output.writeMessage(2, getEvidence());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubmitterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, submitter_);
      }
      if (evidence_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEvidence());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence)) {
        return super.equals(obj);
      }
      proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence other = (proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence) obj;

      boolean result = true;
      result = result && getSubmitter()
          .equals(other.getSubmitter());
      result = result && (hasEvidence() == other.hasEvidence());
      if (hasEvidence()) {
        result = result && getEvidence()
            .equals(other.getEvidence());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBMITTER_FIELD_NUMBER;
      hash = (53 * hash) + getSubmitter().hashCode();
      if (hasEvidence()) {
        hash = (37 * hash) + EVIDENCE_FIELD_NUMBER;
        hash = (53 * hash) + getEvidence().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgSubmitEvidence represents a message that supports submitting arbitrary
     * Evidence of misbehavior such as equivocation or counterfactual signing.
     * </pre>
     *
     * Protobuf type {@code cosmos.evidence.v1beta1.MsgSubmitEvidence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.evidence.v1beta1.MsgSubmitEvidence)
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.class, proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.Builder.class);
      }

      // Construct using proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        submitter_ = "";

        if (evidenceBuilder_ == null) {
          evidence_ = null;
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor;
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence getDefaultInstanceForType() {
        return proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.getDefaultInstance();
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence build() {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence buildPartial() {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence result = new proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence(this);
        result.submitter_ = submitter_;
        if (evidenceBuilder_ == null) {
          result.evidence_ = evidence_;
        } else {
          result.evidence_ = evidenceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence) {
          return mergeFrom((proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence other) {
        if (other == proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence.getDefaultInstance()) return this;
        if (!other.getSubmitter().isEmpty()) {
          submitter_ = other.submitter_;
          onChanged();
        }
        if (other.hasEvidence()) {
          mergeEvidence(other.getEvidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object submitter_ = "";
      /**
       * <code>string submitter = 1;</code>
       */
      public java.lang.String getSubmitter() {
        java.lang.Object ref = submitter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          submitter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string submitter = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubmitterBytes() {
        java.lang.Object ref = submitter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          submitter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string submitter = 1;</code>
       */
      public Builder setSubmitter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        submitter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string submitter = 1;</code>
       */
      public Builder clearSubmitter() {
        
        submitter_ = getDefaultInstance().getSubmitter();
        onChanged();
        return this;
      }
      /**
       * <code>string submitter = 1;</code>
       */
      public Builder setSubmitterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        submitter_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any evidence_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> evidenceBuilder_;
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public boolean hasEvidence() {
        return evidenceBuilder_ != null || evidence_ != null;
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public com.google.protobuf.Any getEvidence() {
        if (evidenceBuilder_ == null) {
          return evidence_ == null ? com.google.protobuf.Any.getDefaultInstance() : evidence_;
        } else {
          return evidenceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public Builder setEvidence(com.google.protobuf.Any value) {
        if (evidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evidence_ = value;
          onChanged();
        } else {
          evidenceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public Builder setEvidence(
          com.google.protobuf.Any.Builder builderForValue) {
        if (evidenceBuilder_ == null) {
          evidence_ = builderForValue.build();
          onChanged();
        } else {
          evidenceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public Builder mergeEvidence(com.google.protobuf.Any value) {
        if (evidenceBuilder_ == null) {
          if (evidence_ != null) {
            evidence_ =
              com.google.protobuf.Any.newBuilder(evidence_).mergeFrom(value).buildPartial();
          } else {
            evidence_ = value;
          }
          onChanged();
        } else {
          evidenceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public Builder clearEvidence() {
        if (evidenceBuilder_ == null) {
          evidence_ = null;
          onChanged();
        } else {
          evidence_ = null;
          evidenceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public com.google.protobuf.Any.Builder getEvidenceBuilder() {
        
        onChanged();
        return getEvidenceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      public com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder() {
        if (evidenceBuilder_ != null) {
          return evidenceBuilder_.getMessageOrBuilder();
        } else {
          return evidence_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : evidence_;
        }
      }
      /**
       * <code>.google.protobuf.Any evidence = 2 [(.cosmos_proto.accepts_interface) = "Evidence"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getEvidenceFieldBuilder() {
        if (evidenceBuilder_ == null) {
          evidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getEvidence(),
                  getParentForChildren(),
                  isClean());
          evidence_ = null;
        }
        return evidenceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.evidence.v1beta1.MsgSubmitEvidence)
    }

    // @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.MsgSubmitEvidence)
    private static final proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence();
    }

    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgSubmitEvidence>
        PARSER = new com.google.protobuf.AbstractParser<MsgSubmitEvidence>() {
      @java.lang.Override
      public MsgSubmitEvidence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgSubmitEvidence(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgSubmitEvidence> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgSubmitEvidence> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidence getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgSubmitEvidenceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * hash defines the hash of the evidence.
     * </pre>
     *
     * <code>bytes hash = 4;</code>
     */
    com.google.protobuf.ByteString getHash();
  }
  /**
   * <pre>
   * MsgSubmitEvidenceResponse defines the Msg/SubmitEvidence response type.
   * </pre>
   *
   * Protobuf type {@code cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse}
   */
  public  static final class MsgSubmitEvidenceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse)
      MsgSubmitEvidenceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgSubmitEvidenceResponse.newBuilder() to construct.
    private MsgSubmitEvidenceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgSubmitEvidenceResponse() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgSubmitEvidenceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {

              hash_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.class, proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString hash_;
    /**
     * <pre>
     * hash defines the hash of the evidence.
     * </pre>
     *
     * <code>bytes hash = 4;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!hash_.isEmpty()) {
        output.writeBytes(4, hash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, hash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse)) {
        return super.equals(obj);
      }
      proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse other = (proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse) obj;

      boolean result = true;
      result = result && getHash()
          .equals(other.getHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgSubmitEvidenceResponse defines the Msg/SubmitEvidence response type.
     * </pre>
     *
     * Protobuf type {@code cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse)
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.class, proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.Builder.class);
      }

      // Construct using proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.cosmos.evidence.v1beta1.Tx.internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor;
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse getDefaultInstanceForType() {
        return proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse build() {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse buildPartial() {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse result = new proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse(this);
        result.hash_ = hash_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse) {
          return mergeFrom((proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse other) {
        if (other == proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse.getDefaultInstance()) return this;
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * hash defines the hash of the evidence.
       * </pre>
       *
       * <code>bytes hash = 4;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <pre>
       * hash defines the hash of the evidence.
       * </pre>
       *
       * <code>bytes hash = 4;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * hash defines the hash of the evidence.
       * </pre>
       *
       * <code>bytes hash = 4;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.MsgSubmitEvidenceResponse)
    private static final proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse();
    }

    public static proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgSubmitEvidenceResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgSubmitEvidenceResponse>() {
      @java.lang.Override
      public MsgSubmitEvidenceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgSubmitEvidenceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgSubmitEvidenceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgSubmitEvidenceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.cosmos.evidence.v1beta1.Tx.MsgSubmitEvidenceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n cosmos/evidence/v1beta1/tx.proto\022\027cosm" +
      "os.evidence.v1beta1\032\024gogoproto/gogo.prot" +
      "o\032\031google/protobuf/any.proto\032\031cosmos_pro" +
      "to/cosmos.proto\"f\n\021MsgSubmitEvidence\022\021\n\t" +
      "submitter\030\001 \001(\t\0224\n\010evidence\030\002 \001(\0132\024.goog" +
      "le.protobuf.AnyB\014\312\264-\010Evidence:\010\350\240\037\000\210\240\037\000\"" +
      ")\n\031MsgSubmitEvidenceResponse\022\014\n\004hash\030\004 \001" +
      "(\0142w\n\003Msg\022p\n\016SubmitEvidence\022*.cosmos.evi" +
      "dence.v1beta1.MsgSubmitEvidence\0322.cosmos" +
      ".evidence.v1beta1.MsgSubmitEvidenceRespo" +
      "nseB#\n\035proto.cosmos.evidence.v1beta1\250\342\036\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          proto.cosmos_proto.Cosmos.getDescriptor(),
        }, assigner);
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidence_descriptor,
        new java.lang.String[] { "Submitter", "Evidence", });
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_evidence_v1beta1_MsgSubmitEvidenceResponse_descriptor,
        new java.lang.String[] { "Hash", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(proto.cosmos_proto.Cosmos.acceptsInterface);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.equalAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    proto.cosmos_proto.Cosmos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
