// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nft/genesis.proto

package proto.nft;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irismod.nft.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<proto.nft.Nft.Collection> 
        getCollectionsList();
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    proto.nft.Nft.Collection getCollections(int index);
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    int getCollectionsCount();
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends proto.nft.Nft.CollectionOrBuilder> 
        getCollectionsOrBuilderList();
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    proto.nft.Nft.CollectionOrBuilder getCollectionsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * GenesisState defines the NFT module's genesis state
   * </pre>
   *
   * Protobuf type {@code irismod.nft.GenesisState}
   */
  public  static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irismod.nft.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      collections_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenesisState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                collections_ = new java.util.ArrayList<proto.nft.Nft.Collection>();
                mutable_bitField0_ |= 0x00000001;
              }
              collections_.add(
                  input.readMessage(proto.nft.Nft.Collection.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          collections_ = java.util.Collections.unmodifiableList(collections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.nft.Genesis.internal_static_irismod_nft_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.nft.Genesis.internal_static_irismod_nft_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.nft.Genesis.GenesisState.class, proto.nft.Genesis.GenesisState.Builder.class);
    }

    public static final int COLLECTIONS_FIELD_NUMBER = 1;
    private java.util.List<proto.nft.Nft.Collection> collections_;
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<proto.nft.Nft.Collection> getCollectionsList() {
      return collections_;
    }
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<? extends proto.nft.Nft.CollectionOrBuilder> 
        getCollectionsOrBuilderList() {
      return collections_;
    }
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    public int getCollectionsCount() {
      return collections_.size();
    }
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    public proto.nft.Nft.Collection getCollections(int index) {
      return collections_.get(index);
    }
    /**
     * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
     */
    public proto.nft.Nft.CollectionOrBuilder getCollectionsOrBuilder(
        int index) {
      return collections_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < collections_.size(); i++) {
        output.writeMessage(1, collections_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < collections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, collections_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.nft.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      proto.nft.Genesis.GenesisState other = (proto.nft.Genesis.GenesisState) obj;

      boolean result = true;
      result = result && getCollectionsList()
          .equals(other.getCollectionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCollectionsCount() > 0) {
        hash = (37 * hash) + COLLECTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getCollectionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.nft.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.nft.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.nft.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.nft.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.nft.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the NFT module's genesis state
     * </pre>
     *
     * Protobuf type {@code irismod.nft.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irismod.nft.GenesisState)
        proto.nft.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.nft.Genesis.internal_static_irismod_nft_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.nft.Genesis.internal_static_irismod_nft_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.nft.Genesis.GenesisState.class, proto.nft.Genesis.GenesisState.Builder.class);
      }

      // Construct using proto.nft.Genesis.GenesisState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCollectionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (collectionsBuilder_ == null) {
          collections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          collectionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.nft.Genesis.internal_static_irismod_nft_GenesisState_descriptor;
      }

      @java.lang.Override
      public proto.nft.Genesis.GenesisState getDefaultInstanceForType() {
        return proto.nft.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public proto.nft.Genesis.GenesisState build() {
        proto.nft.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.nft.Genesis.GenesisState buildPartial() {
        proto.nft.Genesis.GenesisState result = new proto.nft.Genesis.GenesisState(this);
        int from_bitField0_ = bitField0_;
        if (collectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            collections_ = java.util.Collections.unmodifiableList(collections_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.collections_ = collections_;
        } else {
          result.collections_ = collectionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.nft.Genesis.GenesisState) {
          return mergeFrom((proto.nft.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.nft.Genesis.GenesisState other) {
        if (other == proto.nft.Genesis.GenesisState.getDefaultInstance()) return this;
        if (collectionsBuilder_ == null) {
          if (!other.collections_.isEmpty()) {
            if (collections_.isEmpty()) {
              collections_ = other.collections_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCollectionsIsMutable();
              collections_.addAll(other.collections_);
            }
            onChanged();
          }
        } else {
          if (!other.collections_.isEmpty()) {
            if (collectionsBuilder_.isEmpty()) {
              collectionsBuilder_.dispose();
              collectionsBuilder_ = null;
              collections_ = other.collections_;
              bitField0_ = (bitField0_ & ~0x00000001);
              collectionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCollectionsFieldBuilder() : null;
            } else {
              collectionsBuilder_.addAllMessages(other.collections_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.nft.Genesis.GenesisState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.nft.Genesis.GenesisState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.nft.Nft.Collection> collections_ =
        java.util.Collections.emptyList();
      private void ensureCollectionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          collections_ = new java.util.ArrayList<proto.nft.Nft.Collection>(collections_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.nft.Nft.Collection, proto.nft.Nft.Collection.Builder, proto.nft.Nft.CollectionOrBuilder> collectionsBuilder_;

      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.nft.Nft.Collection> getCollectionsList() {
        if (collectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(collections_);
        } else {
          return collectionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public int getCollectionsCount() {
        if (collectionsBuilder_ == null) {
          return collections_.size();
        } else {
          return collectionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.nft.Nft.Collection getCollections(int index) {
        if (collectionsBuilder_ == null) {
          return collections_.get(index);
        } else {
          return collectionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setCollections(
          int index, proto.nft.Nft.Collection value) {
        if (collectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionsIsMutable();
          collections_.set(index, value);
          onChanged();
        } else {
          collectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setCollections(
          int index, proto.nft.Nft.Collection.Builder builderForValue) {
        if (collectionsBuilder_ == null) {
          ensureCollectionsIsMutable();
          collections_.set(index, builderForValue.build());
          onChanged();
        } else {
          collectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addCollections(proto.nft.Nft.Collection value) {
        if (collectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionsIsMutable();
          collections_.add(value);
          onChanged();
        } else {
          collectionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addCollections(
          int index, proto.nft.Nft.Collection value) {
        if (collectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCollectionsIsMutable();
          collections_.add(index, value);
          onChanged();
        } else {
          collectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addCollections(
          proto.nft.Nft.Collection.Builder builderForValue) {
        if (collectionsBuilder_ == null) {
          ensureCollectionsIsMutable();
          collections_.add(builderForValue.build());
          onChanged();
        } else {
          collectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addCollections(
          int index, proto.nft.Nft.Collection.Builder builderForValue) {
        if (collectionsBuilder_ == null) {
          ensureCollectionsIsMutable();
          collections_.add(index, builderForValue.build());
          onChanged();
        } else {
          collectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllCollections(
          java.lang.Iterable<? extends proto.nft.Nft.Collection> values) {
        if (collectionsBuilder_ == null) {
          ensureCollectionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, collections_);
          onChanged();
        } else {
          collectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearCollections() {
        if (collectionsBuilder_ == null) {
          collections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          collectionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeCollections(int index) {
        if (collectionsBuilder_ == null) {
          ensureCollectionsIsMutable();
          collections_.remove(index);
          onChanged();
        } else {
          collectionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.nft.Nft.Collection.Builder getCollectionsBuilder(
          int index) {
        return getCollectionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.nft.Nft.CollectionOrBuilder getCollectionsOrBuilder(
          int index) {
        if (collectionsBuilder_ == null) {
          return collections_.get(index);  } else {
          return collectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends proto.nft.Nft.CollectionOrBuilder> 
           getCollectionsOrBuilderList() {
        if (collectionsBuilder_ != null) {
          return collectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(collections_);
        }
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.nft.Nft.Collection.Builder addCollectionsBuilder() {
        return getCollectionsFieldBuilder().addBuilder(
            proto.nft.Nft.Collection.getDefaultInstance());
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.nft.Nft.Collection.Builder addCollectionsBuilder(
          int index) {
        return getCollectionsFieldBuilder().addBuilder(
            index, proto.nft.Nft.Collection.getDefaultInstance());
      }
      /**
       * <code>repeated .irismod.nft.Collection collections = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.nft.Nft.Collection.Builder> 
           getCollectionsBuilderList() {
        return getCollectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.nft.Nft.Collection, proto.nft.Nft.Collection.Builder, proto.nft.Nft.CollectionOrBuilder> 
          getCollectionsFieldBuilder() {
        if (collectionsBuilder_ == null) {
          collectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.nft.Nft.Collection, proto.nft.Nft.Collection.Builder, proto.nft.Nft.CollectionOrBuilder>(
                  collections_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          collections_ = null;
        }
        return collectionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:irismod.nft.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:irismod.nft.GenesisState)
    private static final proto.nft.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.nft.Genesis.GenesisState();
    }

    public static proto.nft.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenesisState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.nft.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irismod_nft_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irismod_nft_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021nft/genesis.proto\022\013irismod.nft\032\024gogopr" +
      "oto/gogo.proto\032\rnft/nft.proto\"B\n\014Genesis" +
      "State\0222\n\013collections\030\001 \003(\0132\027.irismod.nft" +
      ".CollectionB\004\310\336\037\000B\013\n\tproto.nftb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          proto.nft.Nft.getDescriptor(),
        }, assigner);
    internal_static_irismod_nft_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irismod_nft_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irismod_nft_GenesisState_descriptor,
        new java.lang.String[] { "Collections", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    proto.nft.Nft.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
