// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/crypto/multisig/v1beta1/multisig.proto

package proto.cosmos.crypto.multisig.v1beta1;

public final class Multisig {
  private Multisig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultiSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.crypto.multisig.v1beta1.MultiSignature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getSignaturesList();
    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    int getSignaturesCount();
    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    com.google.protobuf.ByteString getSignatures(int index);
  }
  /**
   * <pre>
   * MultiSignature wraps the signatures from a multisig.LegacyAminoPubKey.
   * See cosmos.tx.v1betata1.ModeInfo.Multi for how to specify which signers
   * signed and with which modes.
   * </pre>
   *
   * Protobuf type {@code cosmos.crypto.multisig.v1beta1.MultiSignature}
   */
  public  static final class MultiSignature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.crypto.multisig.v1beta1.MultiSignature)
      MultiSignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiSignature.newBuilder() to construct.
    private MultiSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiSignature() {
      signatures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiSignature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              signatures_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.class, proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.Builder.class);
    }

    public static final int SIGNATURES_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> signatures_;
    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSignaturesList() {
      return signatures_;
    }
    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <code>repeated bytes signatures = 1;</code>
     */
    public com.google.protobuf.ByteString getSignatures(int index) {
      return signatures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < signatures_.size(); i++) {
        output.writeBytes(1, signatures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < signatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(signatures_.get(i));
        }
        size += dataSize;
        size += 1 * getSignaturesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature)) {
        return super.equals(obj);
      }
      proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature other = (proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature) obj;

      boolean result = true;
      result = result && getSignaturesList()
          .equals(other.getSignaturesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSignaturesCount() > 0) {
        hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getSignaturesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MultiSignature wraps the signatures from a multisig.LegacyAminoPubKey.
     * See cosmos.tx.v1betata1.ModeInfo.Multi for how to specify which signers
     * signed and with which modes.
     * </pre>
     *
     * Protobuf type {@code cosmos.crypto.multisig.v1beta1.MultiSignature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.crypto.multisig.v1beta1.MultiSignature)
        proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.class, proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.Builder.class);
      }

      // Construct using proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature getDefaultInstanceForType() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.getDefaultInstance();
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature build() {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature buildPartial() {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature result = new proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.signatures_ = signatures_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature) {
          return mergeFrom((proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature other) {
        if (other == proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature.getDefaultInstance()) return this;
        if (!other.signatures_.isEmpty()) {
          if (signatures_.isEmpty()) {
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSignaturesIsMutable();
            signatures_.addAll(other.signatures_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> signatures_ = java.util.Collections.emptyList();
      private void ensureSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(signatures_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSignaturesList() {
        return java.util.Collections.unmodifiableList(signatures_);
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public int getSignaturesCount() {
        return signatures_.size();
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public com.google.protobuf.ByteString getSignatures(int index) {
        return signatures_.get(index);
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public Builder setSignatures(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public Builder addSignatures(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public Builder addAllSignatures(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 1;</code>
       */
      public Builder clearSignatures() {
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.crypto.multisig.v1beta1.MultiSignature)
    }

    // @@protoc_insertion_point(class_scope:cosmos.crypto.multisig.v1beta1.MultiSignature)
    private static final proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature();
    }

    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiSignature>
        PARSER = new com.google.protobuf.AbstractParser<MultiSignature>() {
      @java.lang.Override
      public MultiSignature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiSignature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiSignature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiSignature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.cosmos.crypto.multisig.v1beta1.Multisig.MultiSignature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CompactBitArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.crypto.multisig.v1beta1.CompactBitArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 extra_bits_stored = 1;</code>
     */
    int getExtraBitsStored();

    /**
     * <code>bytes elems = 2;</code>
     */
    com.google.protobuf.ByteString getElems();
  }
  /**
   * <pre>
   * CompactBitArray is an implementation of a space efficient bit array.
   * This is used to ensure that the encoded data takes up a minimal amount of
   * space after proto encoding.
   * This is not thread safe, and is not intended for concurrent usage.
   * </pre>
   *
   * Protobuf type {@code cosmos.crypto.multisig.v1beta1.CompactBitArray}
   */
  public  static final class CompactBitArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.crypto.multisig.v1beta1.CompactBitArray)
      CompactBitArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompactBitArray.newBuilder() to construct.
    private CompactBitArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompactBitArray() {
      extraBitsStored_ = 0;
      elems_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompactBitArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              extraBitsStored_ = input.readUInt32();
              break;
            }
            case 18: {

              elems_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.class, proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.Builder.class);
    }

    public static final int EXTRA_BITS_STORED_FIELD_NUMBER = 1;
    private int extraBitsStored_;
    /**
     * <code>uint32 extra_bits_stored = 1;</code>
     */
    public int getExtraBitsStored() {
      return extraBitsStored_;
    }

    public static final int ELEMS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString elems_;
    /**
     * <code>bytes elems = 2;</code>
     */
    public com.google.protobuf.ByteString getElems() {
      return elems_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (extraBitsStored_ != 0) {
        output.writeUInt32(1, extraBitsStored_);
      }
      if (!elems_.isEmpty()) {
        output.writeBytes(2, elems_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (extraBitsStored_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, extraBitsStored_);
      }
      if (!elems_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, elems_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray)) {
        return super.equals(obj);
      }
      proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray other = (proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray) obj;

      boolean result = true;
      result = result && (getExtraBitsStored()
          == other.getExtraBitsStored());
      result = result && getElems()
          .equals(other.getElems());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTRA_BITS_STORED_FIELD_NUMBER;
      hash = (53 * hash) + getExtraBitsStored();
      hash = (37 * hash) + ELEMS_FIELD_NUMBER;
      hash = (53 * hash) + getElems().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CompactBitArray is an implementation of a space efficient bit array.
     * This is used to ensure that the encoded data takes up a minimal amount of
     * space after proto encoding.
     * This is not thread safe, and is not intended for concurrent usage.
     * </pre>
     *
     * Protobuf type {@code cosmos.crypto.multisig.v1beta1.CompactBitArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.crypto.multisig.v1beta1.CompactBitArray)
        proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.class, proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.Builder.class);
      }

      // Construct using proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        extraBitsStored_ = 0;

        elems_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor;
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray getDefaultInstanceForType() {
        return proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.getDefaultInstance();
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray build() {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray buildPartial() {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray result = new proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray(this);
        result.extraBitsStored_ = extraBitsStored_;
        result.elems_ = elems_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray) {
          return mergeFrom((proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray other) {
        if (other == proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray.getDefaultInstance()) return this;
        if (other.getExtraBitsStored() != 0) {
          setExtraBitsStored(other.getExtraBitsStored());
        }
        if (other.getElems() != com.google.protobuf.ByteString.EMPTY) {
          setElems(other.getElems());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int extraBitsStored_ ;
      /**
       * <code>uint32 extra_bits_stored = 1;</code>
       */
      public int getExtraBitsStored() {
        return extraBitsStored_;
      }
      /**
       * <code>uint32 extra_bits_stored = 1;</code>
       */
      public Builder setExtraBitsStored(int value) {
        
        extraBitsStored_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 extra_bits_stored = 1;</code>
       */
      public Builder clearExtraBitsStored() {
        
        extraBitsStored_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString elems_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes elems = 2;</code>
       */
      public com.google.protobuf.ByteString getElems() {
        return elems_;
      }
      /**
       * <code>bytes elems = 2;</code>
       */
      public Builder setElems(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        elems_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes elems = 2;</code>
       */
      public Builder clearElems() {
        
        elems_ = getDefaultInstance().getElems();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.crypto.multisig.v1beta1.CompactBitArray)
    }

    // @@protoc_insertion_point(class_scope:cosmos.crypto.multisig.v1beta1.CompactBitArray)
    private static final proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray();
    }

    public static proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompactBitArray>
        PARSER = new com.google.protobuf.AbstractParser<CompactBitArray>() {
      @java.lang.Override
      public CompactBitArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompactBitArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompactBitArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompactBitArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.cosmos.crypto.multisig.v1beta1.Multisig.CompactBitArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-cosmos/crypto/multisig/v1beta1/multisi" +
      "g.proto\022\036cosmos.crypto.multisig.v1beta1\032" +
      "\024gogoproto/gogo.proto\"*\n\016MultiSignature\022" +
      "\022\n\nsignatures\030\001 \003(\014:\004\320\241\037\001\"A\n\017CompactBitA" +
      "rray\022\031\n\021extra_bits_stored\030\001 \001(\r\022\r\n\005elems" +
      "\030\002 \001(\014:\004\230\240\037\000B&\n$proto.cosmos.crypto.mult" +
      "isig.v1beta1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_crypto_multisig_v1beta1_MultiSignature_descriptor,
        new java.lang.String[] { "Signatures", });
    internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_crypto_multisig_v1beta1_CompactBitArray_descriptor,
        new java.lang.String[] { "ExtraBitsStored", "Elems", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.goprotoUnrecognized);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
