// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record/record.proto

package proto.record;

public final class RecordOuterClass {
  private RecordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irismod.record.Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string digest = 1;</code>
     */
    java.lang.String getDigest();
    /**
     * <code>string digest = 1;</code>
     */
    com.google.protobuf.ByteString
        getDigestBytes();

    /**
     * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
     */
    java.lang.String getDigestAlgo();
    /**
     * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
     */
    com.google.protobuf.ByteString
        getDigestAlgoBytes();

    /**
     * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>string meta = 4;</code>
     */
    java.lang.String getMeta();
    /**
     * <code>string meta = 4;</code>
     */
    com.google.protobuf.ByteString
        getMetaBytes();
  }
  /**
   * <pre>
   * Content defines the detailed information for a record.
   * </pre>
   *
   * Protobuf type {@code irismod.record.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irismod.record.Content)
      ContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() {
      digest_ = "";
      digestAlgo_ = "";
      uri_ = "";
      meta_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              digest_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              digestAlgo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              meta_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.record.RecordOuterClass.internal_static_irismod_record_Content_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.record.RecordOuterClass.internal_static_irismod_record_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.record.RecordOuterClass.Content.class, proto.record.RecordOuterClass.Content.Builder.class);
    }

    public static final int DIGEST_FIELD_NUMBER = 1;
    private volatile java.lang.Object digest_;
    /**
     * <code>string digest = 1;</code>
     */
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digest_ = s;
        return s;
      }
    }
    /**
     * <code>string digest = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIGEST_ALGO_FIELD_NUMBER = 2;
    private volatile java.lang.Object digestAlgo_;
    /**
     * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
     */
    public java.lang.String getDigestAlgo() {
      java.lang.Object ref = digestAlgo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digestAlgo_ = s;
        return s;
      }
    }
    /**
     * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
     */
    public com.google.protobuf.ByteString
        getDigestAlgoBytes() {
      java.lang.Object ref = digestAlgo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digestAlgo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 3;
    private volatile java.lang.Object uri_;
    /**
     * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 4;
    private volatile java.lang.Object meta_;
    /**
     * <code>string meta = 4;</code>
     */
    public java.lang.String getMeta() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meta_ = s;
        return s;
      }
    }
    /**
     * <code>string meta = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMetaBytes() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDigestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, digest_);
      }
      if (!getDigestAlgoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, digestAlgo_);
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
      }
      if (!getMetaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, meta_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDigestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, digest_);
      }
      if (!getDigestAlgoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, digestAlgo_);
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
      }
      if (!getMetaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, meta_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.record.RecordOuterClass.Content)) {
        return super.equals(obj);
      }
      proto.record.RecordOuterClass.Content other = (proto.record.RecordOuterClass.Content) obj;

      boolean result = true;
      result = result && getDigest()
          .equals(other.getDigest());
      result = result && getDigestAlgo()
          .equals(other.getDigestAlgo());
      result = result && getUri()
          .equals(other.getUri());
      result = result && getMeta()
          .equals(other.getMeta());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getDigest().hashCode();
      hash = (37 * hash) + DIGEST_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + getDigestAlgo().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.record.RecordOuterClass.Content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.record.RecordOuterClass.Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Content defines the detailed information for a record.
     * </pre>
     *
     * Protobuf type {@code irismod.record.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irismod.record.Content)
        proto.record.RecordOuterClass.ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Content_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.record.RecordOuterClass.Content.class, proto.record.RecordOuterClass.Content.Builder.class);
      }

      // Construct using proto.record.RecordOuterClass.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        digest_ = "";

        digestAlgo_ = "";

        uri_ = "";

        meta_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Content_descriptor;
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Content getDefaultInstanceForType() {
        return proto.record.RecordOuterClass.Content.getDefaultInstance();
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Content build() {
        proto.record.RecordOuterClass.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Content buildPartial() {
        proto.record.RecordOuterClass.Content result = new proto.record.RecordOuterClass.Content(this);
        result.digest_ = digest_;
        result.digestAlgo_ = digestAlgo_;
        result.uri_ = uri_;
        result.meta_ = meta_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.record.RecordOuterClass.Content) {
          return mergeFrom((proto.record.RecordOuterClass.Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.record.RecordOuterClass.Content other) {
        if (other == proto.record.RecordOuterClass.Content.getDefaultInstance()) return this;
        if (!other.getDigest().isEmpty()) {
          digest_ = other.digest_;
          onChanged();
        }
        if (!other.getDigestAlgo().isEmpty()) {
          digestAlgo_ = other.digestAlgo_;
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getMeta().isEmpty()) {
          meta_ = other.meta_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.record.RecordOuterClass.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.record.RecordOuterClass.Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object digest_ = "";
      /**
       * <code>string digest = 1;</code>
       */
      public java.lang.String getDigest() {
        java.lang.Object ref = digest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string digest = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDigestBytes() {
        java.lang.Object ref = digest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string digest = 1;</code>
       */
      public Builder setDigest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string digest = 1;</code>
       */
      public Builder clearDigest() {
        
        digest_ = getDefaultInstance().getDigest();
        onChanged();
        return this;
      }
      /**
       * <code>string digest = 1;</code>
       */
      public Builder setDigestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digest_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object digestAlgo_ = "";
      /**
       * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
       */
      public java.lang.String getDigestAlgo() {
        java.lang.Object ref = digestAlgo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digestAlgo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
       */
      public com.google.protobuf.ByteString
          getDigestAlgoBytes() {
        java.lang.Object ref = digestAlgo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digestAlgo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
       */
      public Builder setDigestAlgo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digestAlgo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
       */
      public Builder clearDigestAlgo() {
        
        digestAlgo_ = getDefaultInstance().getDigestAlgo();
        onChanged();
        return this;
      }
      /**
       * <code>string digest_algo = 2 [(.gogoproto.moretags) = "yaml:&#92;"digest_algo&#92;""];</code>
       */
      public Builder setDigestAlgoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digestAlgo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 3 [(.gogoproto.customname) = "URI"];</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object meta_ = "";
      /**
       * <code>string meta = 4;</code>
       */
      public java.lang.String getMeta() {
        java.lang.Object ref = meta_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          meta_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string meta = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMetaBytes() {
        java.lang.Object ref = meta_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          meta_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string meta = 4;</code>
       */
      public Builder setMeta(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        meta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string meta = 4;</code>
       */
      public Builder clearMeta() {
        
        meta_ = getDefaultInstance().getMeta();
        onChanged();
        return this;
      }
      /**
       * <code>string meta = 4;</code>
       */
      public Builder setMetaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        meta_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:irismod.record.Content)
    }

    // @@protoc_insertion_point(class_scope:irismod.record.Content)
    private static final proto.record.RecordOuterClass.Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.record.RecordOuterClass.Content();
    }

    public static proto.record.RecordOuterClass.Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      @java.lang.Override
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.record.RecordOuterClass.Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irismod.record.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
     */
    java.lang.String getTxHash();
    /**
     * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
     */
    com.google.protobuf.ByteString
        getTxHashBytes();

    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<proto.record.RecordOuterClass.Content> 
        getContentsList();
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    proto.record.RecordOuterClass.Content getContents(int index);
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    int getContentsCount();
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends proto.record.RecordOuterClass.ContentOrBuilder> 
        getContentsOrBuilderList();
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    proto.record.RecordOuterClass.ContentOrBuilder getContentsOrBuilder(
        int index);

    /**
     * <code>string creator = 3;</code>
     */
    java.lang.String getCreator();
    /**
     * <code>string creator = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();
  }
  /**
   * Protobuf type {@code irismod.record.Record}
   */
  public  static final class Record extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irismod.record.Record)
      RecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Record() {
      txHash_ = "";
      contents_ = java.util.Collections.emptyList();
      creator_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Record(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              txHash_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                contents_ = new java.util.ArrayList<proto.record.RecordOuterClass.Content>();
                mutable_bitField0_ |= 0x00000002;
              }
              contents_.add(
                  input.readMessage(proto.record.RecordOuterClass.Content.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = java.util.Collections.unmodifiableList(contents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.record.RecordOuterClass.internal_static_irismod_record_Record_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.record.RecordOuterClass.internal_static_irismod_record_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.record.RecordOuterClass.Record.class, proto.record.RecordOuterClass.Record.Builder.class);
    }

    private int bitField0_;
    public static final int TX_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object txHash_;
    /**
     * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
     */
    public java.lang.String getTxHash() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txHash_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
     */
    public com.google.protobuf.ByteString
        getTxHashBytes() {
      java.lang.Object ref = txHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private java.util.List<proto.record.RecordOuterClass.Content> contents_;
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<proto.record.RecordOuterClass.Content> getContentsList() {
      return contents_;
    }
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<? extends proto.record.RecordOuterClass.ContentOrBuilder> 
        getContentsOrBuilderList() {
      return contents_;
    }
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    public int getContentsCount() {
      return contents_.size();
    }
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    public proto.record.RecordOuterClass.Content getContents(int index) {
      return contents_.get(index);
    }
    /**
     * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
     */
    public proto.record.RecordOuterClass.ContentOrBuilder getContentsOrBuilder(
        int index) {
      return contents_.get(index);
    }

    public static final int CREATOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object creator_;
    /**
     * <code>string creator = 3;</code>
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>string creator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTxHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txHash_);
      }
      for (int i = 0; i < contents_.size(); i++) {
        output.writeMessage(2, contents_.get(i));
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, creator_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTxHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txHash_);
      }
      for (int i = 0; i < contents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, contents_.get(i));
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, creator_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.record.RecordOuterClass.Record)) {
        return super.equals(obj);
      }
      proto.record.RecordOuterClass.Record other = (proto.record.RecordOuterClass.Record) obj;

      boolean result = true;
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && getContentsList()
          .equals(other.getContentsList());
      result = result && getCreator()
          .equals(other.getCreator());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      if (getContentsCount() > 0) {
        hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
        hash = (53 * hash) + getContentsList().hashCode();
      }
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.record.RecordOuterClass.Record parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.record.RecordOuterClass.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.record.RecordOuterClass.Record prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code irismod.record.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irismod.record.Record)
        proto.record.RecordOuterClass.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Record_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.record.RecordOuterClass.Record.class, proto.record.RecordOuterClass.Record.Builder.class);
      }

      // Construct using proto.record.RecordOuterClass.Record.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        txHash_ = "";

        if (contentsBuilder_ == null) {
          contents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          contentsBuilder_.clear();
        }
        creator_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.record.RecordOuterClass.internal_static_irismod_record_Record_descriptor;
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Record getDefaultInstanceForType() {
        return proto.record.RecordOuterClass.Record.getDefaultInstance();
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Record build() {
        proto.record.RecordOuterClass.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.record.RecordOuterClass.Record buildPartial() {
        proto.record.RecordOuterClass.Record result = new proto.record.RecordOuterClass.Record(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.txHash_ = txHash_;
        if (contentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            contents_ = java.util.Collections.unmodifiableList(contents_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.contents_ = contents_;
        } else {
          result.contents_ = contentsBuilder_.build();
        }
        result.creator_ = creator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.record.RecordOuterClass.Record) {
          return mergeFrom((proto.record.RecordOuterClass.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.record.RecordOuterClass.Record other) {
        if (other == proto.record.RecordOuterClass.Record.getDefaultInstance()) return this;
        if (!other.getTxHash().isEmpty()) {
          txHash_ = other.txHash_;
          onChanged();
        }
        if (contentsBuilder_ == null) {
          if (!other.contents_.isEmpty()) {
            if (contents_.isEmpty()) {
              contents_ = other.contents_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureContentsIsMutable();
              contents_.addAll(other.contents_);
            }
            onChanged();
          }
        } else {
          if (!other.contents_.isEmpty()) {
            if (contentsBuilder_.isEmpty()) {
              contentsBuilder_.dispose();
              contentsBuilder_ = null;
              contents_ = other.contents_;
              bitField0_ = (bitField0_ & ~0x00000002);
              contentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContentsFieldBuilder() : null;
            } else {
              contentsBuilder_.addAllMessages(other.contents_);
            }
          }
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.record.RecordOuterClass.Record parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.record.RecordOuterClass.Record) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object txHash_ = "";
      /**
       * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
       */
      public java.lang.String getTxHash() {
        java.lang.Object ref = txHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
       */
      public com.google.protobuf.ByteString
          getTxHashBytes() {
        java.lang.Object ref = txHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
       */
      public Builder setTxHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      /**
       * <code>string tx_hash = 1 [(.gogoproto.moretags) = "yaml:&#92;"tx_hash&#92;""];</code>
       */
      public Builder setTxHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txHash_ = value;
        onChanged();
        return this;
      }

      private java.util.List<proto.record.RecordOuterClass.Content> contents_ =
        java.util.Collections.emptyList();
      private void ensureContentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new java.util.ArrayList<proto.record.RecordOuterClass.Content>(contents_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.record.RecordOuterClass.Content, proto.record.RecordOuterClass.Content.Builder, proto.record.RecordOuterClass.ContentOrBuilder> contentsBuilder_;

      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.record.RecordOuterClass.Content> getContentsList() {
        if (contentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contents_);
        } else {
          return contentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public int getContentsCount() {
        if (contentsBuilder_ == null) {
          return contents_.size();
        } else {
          return contentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public proto.record.RecordOuterClass.Content getContents(int index) {
        if (contentsBuilder_ == null) {
          return contents_.get(index);
        } else {
          return contentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setContents(
          int index, proto.record.RecordOuterClass.Content value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.set(index, value);
          onChanged();
        } else {
          contentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setContents(
          int index, proto.record.RecordOuterClass.Content.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addContents(proto.record.RecordOuterClass.Content value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.add(value);
          onChanged();
        } else {
          contentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addContents(
          int index, proto.record.RecordOuterClass.Content value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.add(index, value);
          onChanged();
        } else {
          contentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addContents(
          proto.record.RecordOuterClass.Content.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.add(builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addContents(
          int index, proto.record.RecordOuterClass.Content.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllContents(
          java.lang.Iterable<? extends proto.record.RecordOuterClass.Content> values) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contents_);
          onChanged();
        } else {
          contentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearContents() {
        if (contentsBuilder_ == null) {
          contents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          contentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeContents(int index) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.remove(index);
          onChanged();
        } else {
          contentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public proto.record.RecordOuterClass.Content.Builder getContentsBuilder(
          int index) {
        return getContentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public proto.record.RecordOuterClass.ContentOrBuilder getContentsOrBuilder(
          int index) {
        if (contentsBuilder_ == null) {
          return contents_.get(index);  } else {
          return contentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends proto.record.RecordOuterClass.ContentOrBuilder> 
           getContentsOrBuilderList() {
        if (contentsBuilder_ != null) {
          return contentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contents_);
        }
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public proto.record.RecordOuterClass.Content.Builder addContentsBuilder() {
        return getContentsFieldBuilder().addBuilder(
            proto.record.RecordOuterClass.Content.getDefaultInstance());
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public proto.record.RecordOuterClass.Content.Builder addContentsBuilder(
          int index) {
        return getContentsFieldBuilder().addBuilder(
            index, proto.record.RecordOuterClass.Content.getDefaultInstance());
      }
      /**
       * <code>repeated .irismod.record.Content contents = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.record.RecordOuterClass.Content.Builder> 
           getContentsBuilderList() {
        return getContentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.record.RecordOuterClass.Content, proto.record.RecordOuterClass.Content.Builder, proto.record.RecordOuterClass.ContentOrBuilder> 
          getContentsFieldBuilder() {
        if (contentsBuilder_ == null) {
          contentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.record.RecordOuterClass.Content, proto.record.RecordOuterClass.Content.Builder, proto.record.RecordOuterClass.ContentOrBuilder>(
                  contents_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          contents_ = null;
        }
        return contentsBuilder_;
      }

      private java.lang.Object creator_ = "";
      /**
       * <code>string creator = 3;</code>
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string creator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder clearCreator() {
        
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>string creator = 3;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        creator_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:irismod.record.Record)
    }

    // @@protoc_insertion_point(class_scope:irismod.record.Record)
    private static final proto.record.RecordOuterClass.Record DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.record.RecordOuterClass.Record();
    }

    public static proto.record.RecordOuterClass.Record getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Record>
        PARSER = new com.google.protobuf.AbstractParser<Record>() {
      @java.lang.Override
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Record(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Record> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.record.RecordOuterClass.Record getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irismod_record_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irismod_record_Content_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irismod_record_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irismod_record_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023record/record.proto\022\016irismod.record\032\024g" +
      "ogoproto/gogo.proto\"p\n\007Content\022\016\n\006digest" +
      "\030\001 \001(\t\022+\n\013digest_algo\030\002 \001(\tB\026\362\336\037\022yaml:\"d" +
      "igest_algo\"\022\024\n\003uri\030\003 \001(\tB\007\342\336\037\003URI\022\014\n\004met" +
      "a\030\004 \001(\t:\004\350\240\037\001\"u\n\006Record\022#\n\007tx_hash\030\001 \001(\t" +
      "B\022\362\336\037\016yaml:\"tx_hash\"\022/\n\010contents\030\002 \003(\0132\027" +
      ".irismod.record.ContentB\004\310\336\037\000\022\017\n\007creator" +
      "\030\003 \001(\t:\004\350\240\037\001B\022\n\014proto.record\310\341\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_irismod_record_Content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irismod_record_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irismod_record_Content_descriptor,
        new java.lang.String[] { "Digest", "DigestAlgo", "Uri", "Meta", });
    internal_static_irismod_record_Record_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_irismod_record_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irismod_record_Record_descriptor,
        new java.lang.String[] { "TxHash", "Contents", "Creator", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
