// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tibc/core/routing/v1/routing.proto

package proto.tibc.core.routing.v1;

public final class Routing {
  private Routing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SetRoutingRulesProposalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tibc.core.routing.v1.SetRoutingRulesProposal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    java.util.List<java.lang.String>
        getRulesList();
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    int getRulesCount();
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    java.lang.String getRules(int index);
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    com.google.protobuf.ByteString
        getRulesBytes(int index);
  }
  /**
   * <pre>
   * SetRoutingRulesProposal defines a proposal to set routing rules
   * </pre>
   *
   * Protobuf type {@code tibc.core.routing.v1.SetRoutingRulesProposal}
   */
  public  static final class SetRoutingRulesProposal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tibc.core.routing.v1.SetRoutingRulesProposal)
      SetRoutingRulesProposalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetRoutingRulesProposal.newBuilder() to construct.
    private SetRoutingRulesProposal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetRoutingRulesProposal() {
      title_ = "";
      description_ = "";
      rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetRoutingRulesProposal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rules_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              rules_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rules_ = rules_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.tibc.core.routing.v1.Routing.internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.tibc.core.routing.v1.Routing.internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.class, proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the title of the update proposal
     * </pre>
     *
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the description of the proposal
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList rules_;
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRulesList() {
      return rules_;
    }
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    public int getRulesCount() {
      return rules_.size();
    }
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    public java.lang.String getRules(int index) {
      return rules_.get(index);
    }
    /**
     * <pre>
     * routing rules list
     * </pre>
     *
     * <code>repeated string rules = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRulesBytes(int index) {
      return rules_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      for (int i = 0; i < rules_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rules_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rules_.size(); i++) {
          dataSize += computeStringSizeNoTag(rules_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRulesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal)) {
        return super.equals(obj);
      }
      proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal other = (proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getRulesList()
          .equals(other.getRulesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getRulesCount() > 0) {
        hash = (37 * hash) + RULES_FIELD_NUMBER;
        hash = (53 * hash) + getRulesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * SetRoutingRulesProposal defines a proposal to set routing rules
     * </pre>
     *
     * Protobuf type {@code tibc.core.routing.v1.SetRoutingRulesProposal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tibc.core.routing.v1.SetRoutingRulesProposal)
        proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.tibc.core.routing.v1.Routing.internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.tibc.core.routing.v1.Routing.internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.class, proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.Builder.class);
      }

      // Construct using proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        description_ = "";

        rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.tibc.core.routing.v1.Routing.internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor;
      }

      @java.lang.Override
      public proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal getDefaultInstanceForType() {
        return proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.getDefaultInstance();
      }

      @java.lang.Override
      public proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal build() {
        proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal buildPartial() {
        proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal result = new proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        result.description_ = description_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          rules_ = rules_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.rules_ = rules_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal) {
          return mergeFrom((proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal other) {
        if (other == proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.rules_.isEmpty()) {
          if (rules_.isEmpty()) {
            rules_ = other.rules_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRulesIsMutable();
            rules_.addAll(other.rules_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <pre>
       * the title of the update proposal
       * </pre>
       *
       * <code>string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the title of the update proposal
       * </pre>
       *
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the title of the update proposal
       * </pre>
       *
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the title of the update proposal
       * </pre>
       *
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the title of the update proposal
       * </pre>
       *
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * the description of the proposal
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the description of the proposal
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the description of the proposal
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the description of the proposal
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the description of the proposal
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRulesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rules_ = new com.google.protobuf.LazyStringArrayList(rules_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRulesList() {
        return rules_.getUnmodifiableView();
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public int getRulesCount() {
        return rules_.size();
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public java.lang.String getRules(int index) {
        return rules_.get(index);
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRulesBytes(int index) {
        return rules_.getByteString(index);
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public Builder setRules(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRulesIsMutable();
        rules_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public Builder addRules(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRulesIsMutable();
        rules_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public Builder addAllRules(
          java.lang.Iterable<java.lang.String> values) {
        ensureRulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rules_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public Builder clearRules() {
        rules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * routing rules list
       * </pre>
       *
       * <code>repeated string rules = 3;</code>
       */
      public Builder addRulesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRulesIsMutable();
        rules_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tibc.core.routing.v1.SetRoutingRulesProposal)
    }

    // @@protoc_insertion_point(class_scope:tibc.core.routing.v1.SetRoutingRulesProposal)
    private static final proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal();
    }

    public static proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetRoutingRulesProposal>
        PARSER = new com.google.protobuf.AbstractParser<SetRoutingRulesProposal>() {
      @java.lang.Override
      public SetRoutingRulesProposal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetRoutingRulesProposal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetRoutingRulesProposal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetRoutingRulesProposal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.tibc.core.routing.v1.Routing.SetRoutingRulesProposal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"tibc/core/routing/v1/routing.proto\022\024ti" +
      "bc.core.routing.v1\032\024gogoproto/gogo.proto" +
      "\"R\n\027SetRoutingRulesProposal\022\r\n\005title\030\001 \001" +
      "(\t\022\023\n\013description\030\002 \001(\t\022\r\n\005rules\030\003 \003(\t:\004" +
      "\210\240\037\000B\034\n\032proto.tibc.core.routing.v1b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tibc_core_routing_v1_SetRoutingRulesProposal_descriptor,
        new java.lang.String[] { "Title", "Description", "Rules", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
