// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tibc/apps/nft_transfer/v1/nft_transfer.proto

package proto.tibc.apps.nft_transfer.v1;

public final class NftTransfer {
  private NftTransfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NonFungibleTokenPacketDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the class to which the NFT to be transferred belongs
     * </pre>
     *
     * <code>string class = 1;</code>
     */
    java.lang.String getClass_();
    /**
     * <pre>
     * the class to which the NFT to be transferred belongs
     * </pre>
     *
     * <code>string class = 1;</code>
     */
    com.google.protobuf.ByteString
        getClass_Bytes();

    /**
     * <pre>
     * the nft id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <pre>
     * the nft id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * the address defined by NFT outside the chain
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    java.lang.String getUri();
    /**
     * <pre>
     * the address defined by NFT outside the chain
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <pre>
     * the nft sender
     * </pre>
     *
     * <code>string sender = 4;</code>
     */
    java.lang.String getSender();
    /**
     * <pre>
     * the nft sender
     * </pre>
     *
     * <code>string sender = 4;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     * the nft receiver
     * </pre>
     *
     * <code>string receiver = 5;</code>
     */
    java.lang.String getReceiver();
    /**
     * <pre>
     * the nft receiver
     * </pre>
     *
     * <code>string receiver = 5;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <pre>
     * identify whether it is far away from the source chain
     * </pre>
     *
     * <code>bool away_from_origin = 6;</code>
     */
    boolean getAwayFromOrigin();
  }
  /**
   * Protobuf type {@code tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData}
   */
  public  static final class NonFungibleTokenPacketData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData)
      NonFungibleTokenPacketDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NonFungibleTokenPacketData.newBuilder() to construct.
    private NonFungibleTokenPacketData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NonFungibleTokenPacketData() {
      class__ = "";
      id_ = "";
      uri_ = "";
      sender_ = "";
      receiver_ = "";
      awayFromOrigin_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NonFungibleTokenPacketData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              class__ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 48: {

              awayFromOrigin_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.tibc.apps.nft_transfer.v1.NftTransfer.internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.tibc.apps.nft_transfer.v1.NftTransfer.internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.class, proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.Builder.class);
    }

    public static final int CLASS_FIELD_NUMBER = 1;
    private volatile java.lang.Object class__;
    /**
     * <pre>
     * the class to which the NFT to be transferred belongs
     * </pre>
     *
     * <code>string class = 1;</code>
     */
    public java.lang.String getClass_() {
      java.lang.Object ref = class__;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        class__ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the class to which the NFT to be transferred belongs
     * </pre>
     *
     * <code>string class = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClass_Bytes() {
      java.lang.Object ref = class__;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        class__ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * the nft id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the nft id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 3;
    private volatile java.lang.Object uri_;
    /**
     * <pre>
     * the address defined by NFT outside the chain
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the address defined by NFT outside the chain
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object sender_;
    /**
     * <pre>
     * the nft sender
     * </pre>
     *
     * <code>string sender = 4;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the nft sender
     * </pre>
     *
     * <code>string sender = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 5;
    private volatile java.lang.Object receiver_;
    /**
     * <pre>
     * the nft receiver
     * </pre>
     *
     * <code>string receiver = 5;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the nft receiver
     * </pre>
     *
     * <code>string receiver = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AWAY_FROM_ORIGIN_FIELD_NUMBER = 6;
    private boolean awayFromOrigin_;
    /**
     * <pre>
     * identify whether it is far away from the source chain
     * </pre>
     *
     * <code>bool away_from_origin = 6;</code>
     */
    public boolean getAwayFromOrigin() {
      return awayFromOrigin_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClass_Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, class__);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiver_);
      }
      if (awayFromOrigin_ != false) {
        output.writeBool(6, awayFromOrigin_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClass_Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, class__);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiver_);
      }
      if (awayFromOrigin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, awayFromOrigin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData)) {
        return super.equals(obj);
      }
      proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData other = (proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData) obj;

      boolean result = true;
      result = result && getClass_()
          .equals(other.getClass_());
      result = result && getId()
          .equals(other.getId());
      result = result && getUri()
          .equals(other.getUri());
      result = result && getSender()
          .equals(other.getSender());
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && (getAwayFromOrigin()
          == other.getAwayFromOrigin());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASS_FIELD_NUMBER;
      hash = (53 * hash) + getClass_().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + AWAY_FROM_ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAwayFromOrigin());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData)
        proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.tibc.apps.nft_transfer.v1.NftTransfer.internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.tibc.apps.nft_transfer.v1.NftTransfer.internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.class, proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.Builder.class);
      }

      // Construct using proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        class__ = "";

        id_ = "";

        uri_ = "";

        sender_ = "";

        receiver_ = "";

        awayFromOrigin_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.tibc.apps.nft_transfer.v1.NftTransfer.internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor;
      }

      @java.lang.Override
      public proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData getDefaultInstanceForType() {
        return proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.getDefaultInstance();
      }

      @java.lang.Override
      public proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData build() {
        proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData buildPartial() {
        proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData result = new proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData(this);
        result.class__ = class__;
        result.id_ = id_;
        result.uri_ = uri_;
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.awayFromOrigin_ = awayFromOrigin_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData) {
          return mergeFrom((proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData other) {
        if (other == proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData.getDefaultInstance()) return this;
        if (!other.getClass_().isEmpty()) {
          class__ = other.class__;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.getAwayFromOrigin() != false) {
          setAwayFromOrigin(other.getAwayFromOrigin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object class__ = "";
      /**
       * <pre>
       * the class to which the NFT to be transferred belongs
       * </pre>
       *
       * <code>string class = 1;</code>
       */
      public java.lang.String getClass_() {
        java.lang.Object ref = class__;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          class__ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the class to which the NFT to be transferred belongs
       * </pre>
       *
       * <code>string class = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClass_Bytes() {
        java.lang.Object ref = class__;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          class__ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the class to which the NFT to be transferred belongs
       * </pre>
       *
       * <code>string class = 1;</code>
       */
      public Builder setClass_(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        class__ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the class to which the NFT to be transferred belongs
       * </pre>
       *
       * <code>string class = 1;</code>
       */
      public Builder clearClass_() {
        
        class__ = getDefaultInstance().getClass_();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the class to which the NFT to be transferred belongs
       * </pre>
       *
       * <code>string class = 1;</code>
       */
      public Builder setClass_Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        class__ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * the nft id
       * </pre>
       *
       * <code>string id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the nft id
       * </pre>
       *
       * <code>string id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the nft id
       * </pre>
       *
       * <code>string id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft id
       * </pre>
       *
       * <code>string id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft id
       * </pre>
       *
       * <code>string id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <pre>
       * the address defined by NFT outside the chain
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the address defined by NFT outside the chain
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the address defined by NFT outside the chain
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address defined by NFT outside the chain
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the address defined by NFT outside the chain
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <pre>
       * the nft sender
       * </pre>
       *
       * <code>string sender = 4;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the nft sender
       * </pre>
       *
       * <code>string sender = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the nft sender
       * </pre>
       *
       * <code>string sender = 4;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft sender
       * </pre>
       *
       * <code>string sender = 4;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft sender
       * </pre>
       *
       * <code>string sender = 4;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <pre>
       * the nft receiver
       * </pre>
       *
       * <code>string receiver = 5;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the nft receiver
       * </pre>
       *
       * <code>string receiver = 5;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the nft receiver
       * </pre>
       *
       * <code>string receiver = 5;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft receiver
       * </pre>
       *
       * <code>string receiver = 5;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the nft receiver
       * </pre>
       *
       * <code>string receiver = 5;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private boolean awayFromOrigin_ ;
      /**
       * <pre>
       * identify whether it is far away from the source chain
       * </pre>
       *
       * <code>bool away_from_origin = 6;</code>
       */
      public boolean getAwayFromOrigin() {
        return awayFromOrigin_;
      }
      /**
       * <pre>
       * identify whether it is far away from the source chain
       * </pre>
       *
       * <code>bool away_from_origin = 6;</code>
       */
      public Builder setAwayFromOrigin(boolean value) {
        
        awayFromOrigin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * identify whether it is far away from the source chain
       * </pre>
       *
       * <code>bool away_from_origin = 6;</code>
       */
      public Builder clearAwayFromOrigin() {
        
        awayFromOrigin_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData)
    }

    // @@protoc_insertion_point(class_scope:tibc.apps.nft_transfer.v1.NonFungibleTokenPacketData)
    private static final proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData();
    }

    public static proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NonFungibleTokenPacketData>
        PARSER = new com.google.protobuf.AbstractParser<NonFungibleTokenPacketData>() {
      @java.lang.Override
      public NonFungibleTokenPacketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NonFungibleTokenPacketData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NonFungibleTokenPacketData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NonFungibleTokenPacketData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.tibc.apps.nft_transfer.v1.NftTransfer.NonFungibleTokenPacketData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,tibc/apps/nft_transfer/v1/nft_transfer" +
      ".proto\022\031tibc.apps.nft_transfer.v1\032\024gogop" +
      "roto/gogo.proto\"\200\001\n\032NonFungibleTokenPack" +
      "etData\022\r\n\005class\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\013\n\003uri" +
      "\030\003 \001(\t\022\016\n\006sender\030\004 \001(\t\022\020\n\010receiver\030\005 \001(\t" +
      "\022\030\n\020away_from_origin\030\006 \001(\010B!\n\037proto.tibc" +
      ".apps.nft_transfer.v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tibc_apps_nft_transfer_v1_NonFungibleTokenPacketData_descriptor,
        new java.lang.String[] { "Class_", "Id", "Uri", "Sender", "Receiver", "AwayFromOrigin", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
