// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/genesis.proto

package proto.identity;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iritamod.identity.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<proto.identity.IdentityOuterClass.Identity> 
        getIdentitiesList();
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    proto.identity.IdentityOuterClass.Identity getIdentities(int index);
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    int getIdentitiesCount();
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends proto.identity.IdentityOuterClass.IdentityOrBuilder> 
        getIdentitiesOrBuilderList();
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    proto.identity.IdentityOuterClass.IdentityOrBuilder getIdentitiesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * GenesisState defines the identity module's genesis state.
   * </pre>
   *
   * Protobuf type {@code iritamod.identity.GenesisState}
   */
  public  static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iritamod.identity.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      identities_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenesisState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                identities_ = new java.util.ArrayList<proto.identity.IdentityOuterClass.Identity>();
                mutable_bitField0_ |= 0x00000001;
              }
              identities_.add(
                  input.readMessage(proto.identity.IdentityOuterClass.Identity.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          identities_ = java.util.Collections.unmodifiableList(identities_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.identity.Genesis.internal_static_iritamod_identity_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.identity.Genesis.internal_static_iritamod_identity_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.identity.Genesis.GenesisState.class, proto.identity.Genesis.GenesisState.Builder.class);
    }

    public static final int IDENTITIES_FIELD_NUMBER = 1;
    private java.util.List<proto.identity.IdentityOuterClass.Identity> identities_;
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<proto.identity.IdentityOuterClass.Identity> getIdentitiesList() {
      return identities_;
    }
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    public java.util.List<? extends proto.identity.IdentityOuterClass.IdentityOrBuilder> 
        getIdentitiesOrBuilderList() {
      return identities_;
    }
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    public int getIdentitiesCount() {
      return identities_.size();
    }
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    public proto.identity.IdentityOuterClass.Identity getIdentities(int index) {
      return identities_.get(index);
    }
    /**
     * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
     */
    public proto.identity.IdentityOuterClass.IdentityOrBuilder getIdentitiesOrBuilder(
        int index) {
      return identities_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < identities_.size(); i++) {
        output.writeMessage(1, identities_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < identities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, identities_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.identity.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      proto.identity.Genesis.GenesisState other = (proto.identity.Genesis.GenesisState) obj;

      boolean result = true;
      result = result && getIdentitiesList()
          .equals(other.getIdentitiesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdentitiesCount() > 0) {
        hash = (37 * hash) + IDENTITIES_FIELD_NUMBER;
        hash = (53 * hash) + getIdentitiesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.identity.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.identity.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.identity.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.identity.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.identity.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the identity module's genesis state.
     * </pre>
     *
     * Protobuf type {@code iritamod.identity.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iritamod.identity.GenesisState)
        proto.identity.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.identity.Genesis.internal_static_iritamod_identity_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.identity.Genesis.internal_static_iritamod_identity_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.identity.Genesis.GenesisState.class, proto.identity.Genesis.GenesisState.Builder.class);
      }

      // Construct using proto.identity.Genesis.GenesisState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdentitiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (identitiesBuilder_ == null) {
          identities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          identitiesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.identity.Genesis.internal_static_iritamod_identity_GenesisState_descriptor;
      }

      @java.lang.Override
      public proto.identity.Genesis.GenesisState getDefaultInstanceForType() {
        return proto.identity.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public proto.identity.Genesis.GenesisState build() {
        proto.identity.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.identity.Genesis.GenesisState buildPartial() {
        proto.identity.Genesis.GenesisState result = new proto.identity.Genesis.GenesisState(this);
        int from_bitField0_ = bitField0_;
        if (identitiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            identities_ = java.util.Collections.unmodifiableList(identities_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.identities_ = identities_;
        } else {
          result.identities_ = identitiesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.identity.Genesis.GenesisState) {
          return mergeFrom((proto.identity.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.identity.Genesis.GenesisState other) {
        if (other == proto.identity.Genesis.GenesisState.getDefaultInstance()) return this;
        if (identitiesBuilder_ == null) {
          if (!other.identities_.isEmpty()) {
            if (identities_.isEmpty()) {
              identities_ = other.identities_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIdentitiesIsMutable();
              identities_.addAll(other.identities_);
            }
            onChanged();
          }
        } else {
          if (!other.identities_.isEmpty()) {
            if (identitiesBuilder_.isEmpty()) {
              identitiesBuilder_.dispose();
              identitiesBuilder_ = null;
              identities_ = other.identities_;
              bitField0_ = (bitField0_ & ~0x00000001);
              identitiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIdentitiesFieldBuilder() : null;
            } else {
              identitiesBuilder_.addAllMessages(other.identities_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.identity.Genesis.GenesisState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.identity.Genesis.GenesisState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.identity.IdentityOuterClass.Identity> identities_ =
        java.util.Collections.emptyList();
      private void ensureIdentitiesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          identities_ = new java.util.ArrayList<proto.identity.IdentityOuterClass.Identity>(identities_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.identity.IdentityOuterClass.Identity, proto.identity.IdentityOuterClass.Identity.Builder, proto.identity.IdentityOuterClass.IdentityOrBuilder> identitiesBuilder_;

      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.identity.IdentityOuterClass.Identity> getIdentitiesList() {
        if (identitiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(identities_);
        } else {
          return identitiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public int getIdentitiesCount() {
        if (identitiesBuilder_ == null) {
          return identities_.size();
        } else {
          return identitiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.identity.IdentityOuterClass.Identity getIdentities(int index) {
        if (identitiesBuilder_ == null) {
          return identities_.get(index);
        } else {
          return identitiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setIdentities(
          int index, proto.identity.IdentityOuterClass.Identity value) {
        if (identitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdentitiesIsMutable();
          identities_.set(index, value);
          onChanged();
        } else {
          identitiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setIdentities(
          int index, proto.identity.IdentityOuterClass.Identity.Builder builderForValue) {
        if (identitiesBuilder_ == null) {
          ensureIdentitiesIsMutable();
          identities_.set(index, builderForValue.build());
          onChanged();
        } else {
          identitiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addIdentities(proto.identity.IdentityOuterClass.Identity value) {
        if (identitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdentitiesIsMutable();
          identities_.add(value);
          onChanged();
        } else {
          identitiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addIdentities(
          int index, proto.identity.IdentityOuterClass.Identity value) {
        if (identitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdentitiesIsMutable();
          identities_.add(index, value);
          onChanged();
        } else {
          identitiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addIdentities(
          proto.identity.IdentityOuterClass.Identity.Builder builderForValue) {
        if (identitiesBuilder_ == null) {
          ensureIdentitiesIsMutable();
          identities_.add(builderForValue.build());
          onChanged();
        } else {
          identitiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addIdentities(
          int index, proto.identity.IdentityOuterClass.Identity.Builder builderForValue) {
        if (identitiesBuilder_ == null) {
          ensureIdentitiesIsMutable();
          identities_.add(index, builderForValue.build());
          onChanged();
        } else {
          identitiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllIdentities(
          java.lang.Iterable<? extends proto.identity.IdentityOuterClass.Identity> values) {
        if (identitiesBuilder_ == null) {
          ensureIdentitiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, identities_);
          onChanged();
        } else {
          identitiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearIdentities() {
        if (identitiesBuilder_ == null) {
          identities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          identitiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeIdentities(int index) {
        if (identitiesBuilder_ == null) {
          ensureIdentitiesIsMutable();
          identities_.remove(index);
          onChanged();
        } else {
          identitiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.identity.IdentityOuterClass.Identity.Builder getIdentitiesBuilder(
          int index) {
        return getIdentitiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.identity.IdentityOuterClass.IdentityOrBuilder getIdentitiesOrBuilder(
          int index) {
        if (identitiesBuilder_ == null) {
          return identities_.get(index);  } else {
          return identitiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends proto.identity.IdentityOuterClass.IdentityOrBuilder> 
           getIdentitiesOrBuilderList() {
        if (identitiesBuilder_ != null) {
          return identitiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(identities_);
        }
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.identity.IdentityOuterClass.Identity.Builder addIdentitiesBuilder() {
        return getIdentitiesFieldBuilder().addBuilder(
            proto.identity.IdentityOuterClass.Identity.getDefaultInstance());
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public proto.identity.IdentityOuterClass.Identity.Builder addIdentitiesBuilder(
          int index) {
        return getIdentitiesFieldBuilder().addBuilder(
            index, proto.identity.IdentityOuterClass.Identity.getDefaultInstance());
      }
      /**
       * <code>repeated .iritamod.identity.Identity identities = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<proto.identity.IdentityOuterClass.Identity.Builder> 
           getIdentitiesBuilderList() {
        return getIdentitiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.identity.IdentityOuterClass.Identity, proto.identity.IdentityOuterClass.Identity.Builder, proto.identity.IdentityOuterClass.IdentityOrBuilder> 
          getIdentitiesFieldBuilder() {
        if (identitiesBuilder_ == null) {
          identitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.identity.IdentityOuterClass.Identity, proto.identity.IdentityOuterClass.Identity.Builder, proto.identity.IdentityOuterClass.IdentityOrBuilder>(
                  identities_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          identities_ = null;
        }
        return identitiesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iritamod.identity.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:iritamod.identity.GenesisState)
    private static final proto.identity.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.identity.Genesis.GenesisState();
    }

    public static proto.identity.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenesisState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.identity.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iritamod_identity_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iritamod_identity_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026identity/genesis.proto\022\021iritamod.ident" +
      "ity\032\027identity/identity.proto\032\024gogoproto/" +
      "gogo.proto\"E\n\014GenesisState\0225\n\nidentities" +
      "\030\001 \003(\0132\033.iritamod.identity.IdentityB\004\310\336\037" +
      "\000BF\n\016proto.identityZ4github.com/bianjiea" +
      "i/iritamod/modules/identity/typesb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.identity.IdentityOuterClass.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_iritamod_identity_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iritamod_identity_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iritamod_identity_GenesisState_descriptor,
        new java.lang.String[] { "Identities", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    proto.identity.IdentityOuterClass.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
